In [1]:
import numpy as np

In [2]:
## True parameters of our population pdf N(\mu, \sigma)
μ = 5.0
σ = 2.5

In [4]:
## Increasing sample sizes
N = np.array([5*10**n for n in range(1,7)])

In [5]:
N

array([     50,     500,    5000,   50000,  500000, 5000000])

In [6]:
## Empty arrays ready for simulating values
x̄ = np.zeros(6)
b = np.zeros(6)

In [7]:
## The main Monte Carlo simulation loop

for i in range(6):
    x = np.random.normal(μ, σ, size=N[i])
    x̄[i] = np.mean(x)
    b[i] = np.mean(x) - μ

In [8]:
x̄

array([5.28527368, 4.79560183, 5.04002845, 5.00647619, 5.00005632,
       5.00080676])

In [9]:
np.abs(b)

array([2.85273682e-01, 2.04398165e-01, 4.00284541e-02, 6.47619040e-03,
       5.63154130e-05, 8.06764392e-04])