In [1]:
import numpy as np

In [2]:
μ = 5.0
σ = 2.5

In [3]:
N = np.array([5*10**n for n in range(1,7)])

In [4]:
N

array([     50,     500,    5000,   50000,  500000, 5000000])

In [6]:
x̄ = np.zeros(6)
b = np.zeros(6)

In [11]:
for i in range(6):
    x = np.random.normal(μ, σ, size=N[i])
    x̄[i] = np.mean(x)
    b[i] = np.mean(x) - μ

In [12]:
x̄

array([5.39193438, 4.88212444, 5.02657685, 5.00732211, 4.99778816,
       5.0004197 ])

In [14]:
np.abs(b)

array([0.39193438, 0.11787556, 0.02657685, 0.00732211, 0.00221184,
       0.0004197 ])